services:
  - type: web
    name: info-burst
    env: node
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_KEY
        sync: false # Set this value manually in the Render Dashboard
